language: node_js
node_js:
    - "lts/*"
    - "node"
cache:
  directories:
    - "node_modules"
    - "packages/demo/node_modules"
    - "packages/core/node_modules"
install:
    - npm install
    - export PATH=./node_modules/.bin:$PATH
    - lerna bootstrap
